spring:
  elasticsearch:
    uris: ${ELK_REST_URIS:localhost:9200}
    username: ${ELK_USERNAME:}
    password: ${ELK_PASSWORD:}
    ssl_enabled: ${ELK_SSL_ENABLED:false}
    index-config:
      #address-index: ${CUSTOMER_INDEX:adresses_read2test}
      address-index: ${CUSTOMER_INDEX:policy_read}
      address-version-index: ${CUSTOMER_INDEX:adresses_versiontest}
      shards-number: ${INDEX_SHARDS_NUMBER:1}
      replicas-number: ${INDEX_REPLICAS_NUMBER:1}
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 1000
        order_inserts: true

teryt:
  file:
    polling:
      directory: ${TERYT_FILE_DIR:/tmp/teryt}
      cron:
        expression: ${CIS_FILE_POLLING_EXPRESSION:0/30 * * * * *}

logging:
  level:
    com:
      pgoogol:
        teryt:
          integration: ${LOG_LEVEL_ROOT:DEBUG}
